project:
  description: OrePAN2::S3
  author:
    name: Rob Lauer
    mailto: rlauer6@comcast.net
pm_module: OrePAN2::S3
min-perl-version: 5.010
dependencies:
  requires: requires
  test_requires: test-requires
scripts: bin
path:
  pm_module: lib
extra-files:
  - ChangeLog
  - README.md
  - share:
      - orepan2-s3.json
resources:
  homepage: http://github.com/rlauer6/orepan2-s3.git
  bugtracker:
    web: http://github.com/rlauer6/orepan2-s3/issues
    mailto: rlauer6@comcast.net
  repository:
    url: git://github.com/rlauer6/orepan2-s3.git
    web: http://github.com/rlauer6/orepan2-s3
    type: 'git'
